### ISSUE TITLE
Revoking users' certificates as admin not possible

### ISSUE THREAD

**Issue by jornane** [eduvpn/vpn-user-portal#186]
It is currently impossible to revoke certificates from a certain user. Disabling a user will render all certificates unusable, but this is a suboptimal solution because user disabling is typically done in the IdP.

The portal does seem to correctly revoke certificates created by the official clients (they disappear when disabling a user and don't return opun enabling), but not manually created certificates.

The portal should revoke all certificates when disabling a user, and not restore them when enabling the user again.

**Comment by fkooman** [comment]
That is correct. It is not possible to delete certificates from manually created configurations in the portal. This is done on purpose (historically, from the time we didn't have eduVPN/Let's Connect! applications). The eduVPN/Let's Connect! applications will recover themselves, i.e. trigger authorization/authentication after re-enabling a user, so there it is not a problem to revoke all certificates/OAuth authorizations, but there is no such "feedback" when using manually created configurations. 

We had this scenario for cases where someone's device was infected with malware, we disabled their account, they removed the malware and we enable the account again. Then it is really annoying when your certificates are revoked, especially when using multiple devices.

From what you describe, it seems what you are looking for is a "Delete User" and not a "Disable User" option.

This is implemented in 3.x, but not in 2.x because that is quite difficult to do properly there because there are two different databases. See [USER_DELETE](https://github.com/eduvpn/documentation/blob/v2/USER_DELETE.md) on how to delete a user account manually in eduVPN 2.x.

P.S.: in 3.x the difference between "Disable User" and "Delete User" is (next to not deleting manual downloaded certs) that "Delete User" will also remove the "is disabled" flag, which means that the user can again login when they were previously disabled when using external authentication sources. When using the local authentication source this is not a problem as the complete account is deleted so the user won't be able to login anymore.

**Comment by fkooman** [comment]
> So you're saying it's by design that admins cannot revoke users' certificates?

Yes.

**Comment by jornane** [comment]
In that case, please consider this as a feature request.

**Comment by fkooman** [comment]
I backported "Delete User Data" from v3 to v2.

This does not resolve the problem where if a user is already logged in and then gets disabled in the IdP, the SP will not know and assume the session is valid. So unless there is some SAML session ID invalidation implemented on the SP or VPN portal, users could still use the portal when the admin merely deleted their user data and they already had a valid SAML session going. I think it goes a bit far to also implement this.

Only "Disable User" will prevent this from being possible...

**Comment by fkooman** [comment]
In 3.x deleting a user's data (or deleting a user) when that user is still actively logged in will now trigger logout for that user and thus close this hole. I'm not sure this is possible quite as easy with the 2.x authentication architecture...

**Comment by fkooman** [comment]
there's another problem: deleting an account (or account data) should also disconnect the user. I think the cron will take care of this within the hour, but maybe that should also be instant, just like with "Disable".

**Comment by fkooman** [comment]
properly implemented in 3.x, also showing a warning when using external authentication source. Text requires work.

![image](https://user-images.githubusercontent.com/616885/120551047-e4ebe200-c3f5-11eb-8f52-67cc97470edd.png)

**Comment by fkooman** [comment]
As for eduVPN/Let's Connect! 2.x, it will look like this:

![image](https://user-images.githubusercontent.com/616885/120773170-5bd1c980-c521-11eb-88de-1ea251968283.png)

![image](https://user-images.githubusercontent.com/616885/120773221-6be9a900-c521-11eb-8871-ada5f7db9368.png)
