### ISSUE TITLE
investigate not showing oauth confirm dialog

### ISSUE THREAD

**Issue by fkooman** [eduvpn/vpn-user-portal#48]
if we support only registered clients, it may not be needed to ask for approval, but it feels like this could be a security issue...

@sveeke

**Comment by sveeke** [comment]
What is the use of the approval screen when users will always press approve? They already must login with SAML so it's not like someone else (without an account on the IdP) can get to the point of oauth approval requests right? And if that would be possible, then the hacker will approve it himselfright?

What is the use-case of the approval? It looks like a check if the user really wants the server to sent a login token to the app that is requesting it, but that is sort-off obvious already because why would the user go through all the trouble of logging in with IdP (sometimes even with the second factor) if he does not want to use the app when oauth approval is being requested?

**Comment by fkooman** [comment]
I am mostly worried about CSRF here, not so much the obvious usage scenario, because then you are right of course :-)

**Comment by fkooman** [comment]
An attacker could redirect a user to the authorize endpoint, and in that case automatically redirect to `vpn://import` with the `access_token` in the fragment. As the attacker cannot change the `redirect_uri` to anything else than `vpn://import`, I _think_ it is actually fine...

**Comment by sveeke** [comment]
Some thought of a noob ;).

Can the output to vpn://import be intercepted then by some malicous app that is also 'listening' to vpn://import? Is this registered as a protocol in Android? Then the user will be presented a choice (which app to choose) right? 

Isn't there some sort of solution where the app and server share a secret key that will be transmitted within the request? Then the authenticity of the app can be validated right? Or will this secret be to easy to intercept?

**Comment by fkooman** [comment]
The OAuth server from version 2.1.0 (not released yet) supports disabling the "approval" dialog, this is also implemented in vpn-user-portal now,  but also not released yet. 

The default will be to show the dialog, we can disable it for eduVPN instances of course...

**Comment by fkooman** [comment]
released.
